# Generated by Django 3.2.6 on 2021-08-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=65)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField(blank=True)),
                ('category', models.CharField(max_length=50)),
                ('brand', models.CharField(choices=[('Samsung', 'samsung'), ('Apple', 'apple'), ('Xiaomi', 'xiaomi'), ('Huawei', 'huawei')], max_length=10)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
