# Generated by Django 3.2.6 on 2021-08-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_productsimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
